-- Hong Kong Education Funding Monitor System
-- Seed Data for Initial Setup
-- 香港教育資助監測系統初始數據

-- ===================
-- Insert Funding Sources 插入資助來源
-- ===================
INSERT INTO funding_sources (name, name_zh, short_name, url, category) VALUES
('Quality Education Fund', '優質教育基金', 'QEF', 'https://www.qef.org.hk', 'government'),
('Innovation and Technology Fund', '創新科技基金', 'ITF', 'https://www.itf.gov.hk', 'government'),
('Social Innovation and Entrepreneurship Development Fund', '社會創新及創業發展基金', 'SIE Fund', 'https://www.sie.gov.hk', 'government'),
('Committee on the Promotion of Civic Education', '公民教育委員會', 'CPCE', 'https://www.cpce.gov.hk', 'government'),
('Environment and Conservation Fund', '環境及自然保育基金', 'ECF', 'https://www.ecf.gov.hk', 'government'),
('Youth Development Fund', '青年發展基金', 'YDF', 'https://www.ydc.gov.hk', 'government'),
('Standing Committee on Language Education and Research', '語常會', 'SCOLAR', 'https://scolarhk.edb.hkedcity.net', 'government'),
('Arts Development Council', '藝術發展局', 'ADC', 'https://www.hkadc.org.hk', 'government'),
('Commission on Children', '兒童事務委員會', 'CoC', 'https://www.coc.gov.hk', 'government'),
('Home Affairs Department', '民政事務總署', 'HAD', 'https://www.had.gov.hk', 'government'),
('Government News', '政府新聞網', 'GovNews', 'https://www.news.gov.hk', 'government'),
('Hong Kong Jockey Club Charities Trust', '香港賽馬會慈善信託基金', 'HKJC', 'https://charities.hkjc.com', 'foundation'),
('Partnership Fund for the Disadvantaged', '攜手扶弱基金', 'PFD', 'https://www.swd.gov.hk', 'foundation'),
('Cyberport', '數碼港', 'Cyberport', 'https://www.cyberport.hk', 'corporate'),
('Hong Kong Science and Technology Parks', '香港科技園', 'HKSTP', 'https://www.hkstp.org', 'corporate'),
('Hong Kong Innovation Foundation', '香港創新基金', 'HKIF', 'https://hkif.org.hk', 'foundation'),
('Chinese Temples Committee', '華人廟宇委員會', 'CTC', 'https://www.ctc.org.hk', 'foundation'),
('Beat Drugs Fund', '禁毒基金', 'BDF', 'https://www.nd.gov.hk', 'government')
ON CONFLICT DO NOTHING;

-- ===================
-- Insert Sample Funding Programs 插入示例資助計劃
-- ===================

-- Get source IDs for reference
WITH source_ids AS (
    SELECT id, short_name FROM funding_sources
)
INSERT INTO funding_programs (
    source_id, name, name_zh, organization, organization_zh, 
    category, description, description_zh, max_amount, 
    application_period, deadline, status, relevance, url
)
SELECT 
    s.id,
    p.name,
    p.name_zh,
    p.organization,
    p.organization_zh,
    p.category,
    p.description,
    p.description_zh,
    p.max_amount,
    p.application_period,
    p.deadline::date,
    p.status,
    p.relevance,
    p.url
FROM (VALUES
    ('QEF', 
     'AI Education Funding Scheme', 
     '「智」為學理AI教育撥款計劃',
     'Quality Education Fund',
     '優質教育基金',
     '創科教育',
     'Dedicated HK$2 billion funding for AI education projects',
     '專項20億港元撥款，支援學校推行AI教學',
     'HK$200萬',
     '2025年10月 - 2026年1月',
     '2026-01-31',
     'open',
     'high',
     'https://www.qef.org.hk'),
    ('QEF',
     'Priority Theme Scheme Round 16',
     '優先主題計劃第16期',
     'Quality Education Fund',
     '優質教育基金',
     'STEAM教育',
     'Priority themes include STEAM education and values education',
     '優先主題包括STEAM教育及價值觀教育',
     'HK$20萬',
     '2026年4月 - 2026年7月',
     '2026-07-31',
     'upcoming',
     'high',
     'https://www.qef.org.hk'),
    ('ITF',
     'General Support Programme',
     '一般支援計劃',
     'Innovation and Technology Fund',
     '創新科技署',
     '創科推廣',
     'Support non-R&D projects promoting innovation culture',
     '支援非研發項目，推廣香港創新科技文化',
     '按項目而定',
     '全年接受申請',
     NULL,
     'open',
     'high',
     'https://www.itf.gov.hk'),
    ('PFD',
     'After School Care Programme Fund',
     '課餘託管計劃專項基金',
     'Partnership Fund for the Disadvantaged',
     '攜手扶弱基金',
     '青年教育',
     'Support after-school learning for underprivileged students',
     '為基層學生提供課餘學習支援',
     '配對形式',
     '2025年12月18日 - 2026年10月30日',
     '2026-10-30',
     'open',
     'high',
     'https://www.swd.gov.hk'),
    ('CPCE',
     'Civic Education Activities Subsidy Scheme',
     '公民教育活動資助計劃',
     'Committee on the Promotion of Civic Education',
     '公民教育委員會',
     '公民教育',
     'Support civic education activities including patriotism and Chinese culture',
     '資助公民教育活動，包括愛國主義教育及中華文化推廣',
     'HK$15萬',
     '2026年9月 - 2026年10月（預計）',
     '2026-10-31',
     'upcoming',
     'medium',
     'https://www.cpce.gov.hk'),
    ('SIE Fund',
     'Capacity Building Programme',
     '能力提升計劃',
     'Social Innovation and Entrepreneurship Development Fund',
     '社會創新及創業發展基金',
     '社會創新',
     'Support innovative projects addressing poverty and social isolation',
     '支援創新項目解決貧窮及社會孤立問題',
     '按項目而定',
     '全年接受申請',
     NULL,
     'open',
     'medium',
     'https://www.sie.gov.hk'),
    ('ECF',
     'Environmental Education and Community Action Projects',
     '環境教育及社區參與項目',
     'Environment and Conservation Fund',
     '環境及自然保育基金',
     '環保教育',
     'Support environmental education activities',
     '資助環境教育活動',
     'HK$200萬',
     '全年接受申請',
     NULL,
     'open',
     'medium',
     'https://www.ecf.gov.hk'),
    ('YDF',
     'Youth Development Fund Funding Scheme',
     '青年發展基金資助計劃',
     'Youth Development Fund',
     '青年發展基金',
     '青年發展',
     'Support youth entrepreneurship and exchange programmes',
     '支援青年創業及交流計劃',
     '按項目而定',
     '全年接受申請',
     NULL,
     'open',
     'high',
     'https://www.ydc.gov.hk'),
    ('HKJC',
     'CoolThink@JC',
     '賽馬會運算思維教育',
     'Hong Kong Jockey Club Charities Trust',
     '香港賽馬會慈善信託基金',
     '創科教育',
     'Computational thinking education for primary schools',
     '小學運算思維教育計劃',
     '按合作形式',
     '需主動聯絡提案',
     NULL,
     'open',
     'high',
     'https://charities.hkjc.com'),
    ('HKIF',
     'STEAM Education Support',
     'STEAM教育支援計劃',
     'Hong Kong Innovation Foundation',
     '香港創新基金',
     'STEAM教育',
     'Free STEAM courses for underprivileged students',
     '為基層學生提供免費STEAM課程',
     '按合作形式',
     '全年接受申請',
     NULL,
     'open',
     'high',
     'https://hkif.org.hk')
) AS p(source_short, name, name_zh, organization, organization_zh, category, description, description_zh, max_amount, application_period, deadline, status, relevance, url)
JOIN source_ids s ON s.short_name = p.source_short
ON CONFLICT DO NOTHING;

-- Verify data inserted
SELECT 'Funding Sources:' as info, COUNT(*) as count FROM funding_sources
UNION ALL
SELECT 'Funding Programs:', COUNT(*) FROM funding_programs;
